#map_type: "vlmap" # "vlmap", "gt", "clip", "clip_gradcam", "vlmaps_lseg_3d"
maximum_height: 2.5
cam_calib_mat: [386.0, 0.0, 321.0, 0.0, 386.0, 238.0, 0.0, 0.0, 1.0]
use_camera_info_topic: True
camera_info_topic: "/cer/realsense_repeater/camera_info"
grid_size: 1000
cell_size: 0.05
map_save_dir: "/home/ergocub"
map_name: "vlmaps.h5df"
img_topic_name: "/cer/realsense_repeater/color_image"
depth_topic_name: "/cer/realsense_repeater/depth_image"
amcl_cov_threshold: 0.02
target_frame: "map"
use_raycasting: True
raycasting_algorythm: "distance_based"
voxel_offset: 3
raycast_distance_threshold: 0.9
seg_vis: False
live_indexing: True

potential_obstacle_names:
  - "chair"
  - "wall"
  - "wall above the door"
  - "table"
  - "window"
  - "floor"
  - "stairs"
  - "other"
obstacle_names:
  - "wall"
  - "chair"
  - "table"
  - "window"
  - "stairs"
  - "other"
labels:
  - "other"
  - "screen"
  - "table"
  - "closet"
  - "chair"
  - "shelf"
  - "door"
  - "wall"
  - "ceiling"
  - "floor"
  - "human"
classes_to_skip:
  - "human"
categories: "mp3d"

#depth_sample_rate: 30   #100
#dilate_iter: 3
#gaussian_sigma: 1.0
#customize_obstacle_map: False
#potential_obstacle_names:
#  - "chair"
#  - "wall"
#  - "wall above the door"
#  - "table"
#  - "window"
#  - "floor"
#  - "stairs"
#  - "other"
#obstacle_names:
#  - "wall"
#  - "chair"
#  - "table"
#  - "window"
#  - "stairs"
#  - "other"
#categories: "mp3d" # "mp3d", "ai2thor"
